version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
  pre_build:
    commands:
      - echo In the pre_build phase...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync dist/ADMAngJuly25/browser/ s3://$S3_BUCKET_NAME --delete
artifacts:
  files:
    - "**/*"
  base-directory: "dist/ADMAngJuly25/browser"
  discard-paths: no